name 'npajtic-elk-linux'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures npajtic-elk-linux'
long_description 'Installs/Configures npajtic-elk-linux'
version '0.1.0'
