name 'npajtic-lamp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures npajtic-lamp'
long_description 'Installs/Configures npajtic-lamp'
version '0.1.0'
