name 'npajtic-jenkins-linux'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures npajtic-jenkins-linux'
long_description 'Installs/Configures npajtic-jenkins-linux'
version '0.1.0'
